// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: curium/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetAdminAddressRequest struct {
}

func (m *QueryGetAdminAddressRequest) Reset()         { *m = QueryGetAdminAddressRequest{} }
func (m *QueryGetAdminAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAdminAddressRequest) ProtoMessage()    {}
func (*QueryGetAdminAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aeccfed53bdb634, []int{0}
}
func (m *QueryGetAdminAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAdminAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAdminAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAdminAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAdminAddressRequest.Merge(m, src)
}
func (m *QueryGetAdminAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAdminAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAdminAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAdminAddressRequest proto.InternalMessageInfo

type QueryGetAdminAddressResponse struct {
	AdminAddress string `protobuf:"bytes,1,opt,name=adminAddress,proto3" json:"adminAddress,omitempty"`
}

func (m *QueryGetAdminAddressResponse) Reset()         { *m = QueryGetAdminAddressResponse{} }
func (m *QueryGetAdminAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAdminAddressResponse) ProtoMessage()    {}
func (*QueryGetAdminAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1aeccfed53bdb634, []int{1}
}
func (m *QueryGetAdminAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAdminAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAdminAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAdminAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAdminAddressResponse.Merge(m, src)
}
func (m *QueryGetAdminAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAdminAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAdminAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAdminAddressResponse proto.InternalMessageInfo

func (m *QueryGetAdminAddressResponse) GetAdminAddress() string {
	if m != nil {
		return m.AdminAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryGetAdminAddressRequest)(nil), "curium.QueryGetAdminAddressRequest")
	proto.RegisterType((*QueryGetAdminAddressResponse)(nil), "curium.QueryGetAdminAddressResponse")
}

func init() { proto.RegisterFile("curium/query.proto", fileDescriptor_1aeccfed53bdb634) }

var fileDescriptor_1aeccfed53bdb634 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3f, 0x4b, 0x03, 0x31,
	0x18, 0xc6, 0x1b, 0xc1, 0x82, 0x41, 0x10, 0x32, 0x49, 0xad, 0x41, 0x4e, 0x07, 0xff, 0xe0, 0x85,
	0xea, 0xe4, 0xd8, 0x2e, 0xce, 0xd6, 0xcd, 0xa5, 0x24, 0x77, 0x2f, 0x67, 0xe0, 0x2e, 0x49, 0x2f,
	0x89, 0x58, 0x47, 0xbf, 0x80, 0x82, 0x93, 0xdf, 0xc8, 0xb1, 0xe0, 0xe2, 0x28, 0x77, 0x7e, 0x10,
	0xf1, 0xd2, 0xc3, 0x3f, 0x48, 0xa7, 0xbc, 0x3c, 0xf9, 0xbd, 0x0f, 0xcf, 0xfb, 0x60, 0x92, 0xf8,
	0x52, 0xfa, 0x82, 0x4d, 0x3d, 0x94, 0xb3, 0xd8, 0x94, 0xda, 0x69, 0xd2, 0x0d, 0x5a, 0xaf, 0x9f,
	0x69, 0x9d, 0xe5, 0xc0, 0xb8, 0x91, 0x8c, 0x2b, 0xa5, 0x1d, 0x77, 0x52, 0x2b, 0x1b, 0xa8, 0xde,
	0x61, 0xa2, 0x6d, 0xa1, 0x2d, 0x13, 0xdc, 0x42, 0x58, 0x67, 0x37, 0x03, 0x01, 0x8e, 0x0f, 0x98,
	0xe1, 0x99, 0x54, 0x0d, 0x1c, 0xd8, 0x68, 0x1b, 0x6f, 0x5d, 0x7c, 0x11, 0xe7, 0xe0, 0x86, 0x69,
	0x21, 0xd5, 0x30, 0x4d, 0x4b, 0xb0, 0x76, 0x0c, 0x53, 0x0f, 0xd6, 0x45, 0x23, 0xdc, 0xff, 0xff,
	0xdb, 0x1a, 0xad, 0x2c, 0x90, 0x08, 0xaf, 0xf3, 0x1f, 0xfa, 0x26, 0xda, 0x41, 0xfb, 0x6b, 0xe3,
	0x5f, 0xda, 0xc9, 0x33, 0xc2, 0xab, 0x8d, 0x09, 0x79, 0x40, 0x78, 0xe3, 0x8f, 0x13, 0xd9, 0x8d,
	0xc3, 0x4d, 0xf1, 0x92, 0x18, 0xbd, 0xbd, 0xe5, 0x50, 0x08, 0x13, 0x0d, 0xee, 0x5f, 0x3f, 0x9e,
	0x56, 0x8e, 0xc8, 0x01, 0x13, 0xb9, 0xbf, 0x83, 0x3c, 0x07, 0xb6, 0xe8, 0x70, 0xf1, 0x64, 0xe0,
	0x26, 0x4d, 0xb4, 0x09, 0x0f, 0xab, 0xa3, 0xcb, 0x97, 0x8a, 0xa2, 0x79, 0x45, 0xd1, 0x7b, 0x45,
	0xd1, 0x63, 0x4d, 0x3b, 0xf3, 0x9a, 0x76, 0xde, 0x6a, 0xda, 0xb9, 0x3a, 0xcb, 0xa4, 0xbb, 0xf6,
	0x22, 0x4e, 0x74, 0xf1, 0x6d, 0xd7, 0x0e, 0xc7, 0xc6, 0x8b, 0x5c, 0x26, 0xad, 0xef, 0x6d, 0x3b,
	0xb8, 0x99, 0x01, 0x2b, 0xba, 0x4d, 0xb5, 0xa7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xee, 0x2b,
	0x7c, 0xa8, 0xc2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries the admin address.
	GetAdminAddress(ctx context.Context, in *QueryGetAdminAddressRequest, opts ...grpc.CallOption) (*QueryGetAdminAddressResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetAdminAddress(ctx context.Context, in *QueryGetAdminAddressRequest, opts ...grpc.CallOption) (*QueryGetAdminAddressResponse, error) {
	out := new(QueryGetAdminAddressResponse)
	err := c.cc.Invoke(ctx, "/curium.Query/GetAdminAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries the admin address.
	GetAdminAddress(context.Context, *QueryGetAdminAddressRequest) (*QueryGetAdminAddressResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetAdminAddress(ctx context.Context, req *QueryGetAdminAddressRequest) (*QueryGetAdminAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdminAddress not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetAdminAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAdminAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAdminAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/curium.Query/GetAdminAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAdminAddress(ctx, req.(*QueryGetAdminAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "curium.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdminAddress",
			Handler:    _Query_GetAdminAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "curium/query.proto",
}

func (m *QueryGetAdminAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAdminAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAdminAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetAdminAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAdminAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAdminAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AdminAddress) > 0 {
		i -= len(m.AdminAddress)
		copy(dAtA[i:], m.AdminAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AdminAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetAdminAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetAdminAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AdminAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetAdminAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAdminAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAdminAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAdminAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAdminAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAdminAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdminAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdminAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
