syntax = "proto3";
package storage;
import "gogoproto/gogo.proto";
import "cosmos/msg/v1/msg.proto";

// this line is used by starport scaffolding # proto/tx/import

option go_package = "github.com/bluzelle/bluzelle-public/curium/x/storage/types";

// Msg defines the Msg service.
service Msg {
      rpc Pin(MsgPin) returns (MsgPinResponse);
// this line is used by starport scaffolding # proto/tx/rpc
}

message MsgPin {
  option (cosmos.msg.v1.signer) = "creator";
  string creator = 1;
  string cid = 2;
  repeated string addrs = 3 [ (gogoproto.nullable) = false ];
}

message MsgPinResponse {
}

// this line is used by starport scaffolding # proto/tx/message